AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Cloudformation template to deploy the Kitten Carousel Web Application 

# Parameters:

Resources:

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and SSH for webser
      GroupName: WebServerSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80 
          CidrIp: 0.0.0.0/0
  
  MyWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b5eea76982371e91
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroupIds: 
         - ! Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: WebServer-Berkay
      UserData:
        Fn::Base64:
        |
          #!/bin/bash -x
          yum update -y
          yum install httpd -y
          cd/var/www/html
          
# Outputs: